# Generated by Django 5.2.4 on 2025-07-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('Maize', 'Maize'), ('Pepper', 'Pepper'), ('Yam', 'Yam')], default='Tomato', max_length=20),
        ),
    ]
