# Generated by Django 5.2.4 on 2025-08-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_description_alter_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.CharField(default='Oyo State', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tomato', 'Tomato'), ('Maize', 'Maize'), ('Pepper', 'Pepper'), ('Yam', 'Yam'), ('Cassava', 'Cassava'), ('Rice', 'Rice'), ('Okra', 'Okra'), ('Onion', 'Onion'), ('Cucumber', 'Cucumber'), ('Carrot', 'Carrot'), ('Eggplant', 'Eggplant'), ('Watermelon', 'Watermelon')], default='Tomato', max_length=20),
        ),
    ]
