# Generated by Django 5.2.4 on 2025-08-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
    ]
