# Generated by Django 5.2.4 on 2025-08-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='requested_for_group',
            field=models.BooleanField(default=False),
        ),
    ]
