# Generated by Django 5.2.4 on 2025-08-14 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_deliveryrequest_requested_for_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_delivery_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_delivery_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
