# Generated by Django 5.2.4 on 2025-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_message_subject_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
